bot:
  api-url: https://api.capybarameme.com
  refer-url: https://bot.capybarameme.com/

query-file: "query.txt"
auto-spin: true
auto-stake: true
amount-stake: 0.5
max-thread: 10
random-sleep:
  min: 1800
  max: 3600
