version: '3'
services:
  bot:
    container_name: 'CapybaraMeme'
    image: capymeme-bot
    stop_signal: SIGINT
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "3"
